### ISSUE TITLE
Header menu / last item has hardcoded dropdown items 

### ISSUE THREAD

**Issue by DanielLeyUX** [kickstartDS/cooper-website#10]
On both websites, the last menu item comes with a dropdown, although in global settings no sub-items have been setup.

please fix, thanks

![image](https://github.com/user-attachments/assets/6cec03ed-5a0b-427e-99db-6f6ab5b46de3)

**Comment by julrich** [comment]
Fixed manually, it's mainly the preset that's broken here. Deleted the offending `navItem` (which had the invisible sub menu), and just re-created it manually. If the whole `Header` is added manually, the problem never arises.

Small additional, but unrelated, bug was the schema mismatch (`1 item out of schema` for `type: navItems`), which resulted from a missing `type` field on `navItems`.

Tracked for the Starter here: https://github.com/kickstartDS/storyblok-starter/issues/30
