### ISSUE TITLE
Aspect ratio related props have no effect (e.g. `Gallery`)

### ISSUE THREAD

**Issue by DanielLeyUX** [kickstartDS/cooper-website#11]
Aspect Ratio prop has no effect, please check

![image](https://github.com/user-attachments/assets/7af991f1-d01e-42ff-a176-13f18806f17f)

All potentially affected components:
* [x] `Gallery`
* [x] `Image Story`
* [ ] `Html` -> https://github.com/kickstartDS/cooper-website/issues/16
* [ ] `Image`
* [ ] `Contact`
* [ ] `Teaser Card`

**Comment by julrich** [comment]
Fixed this for the Gallery case, but additional fixes will be needed for other components utilizing aspect ratios:
https://github.com/search?q=repo%3AkickstartDS%2Fds-agency-premium+ratio+path%3A**%2F*Component.tsx&type=code

**Comment by julrich** [comment]
Fixed now!

Starter issue here: https://github.com/kickstartDS/storyblok-starter-premium/issues/24
