### ISSUE TITLE
Header-Nav: Z-index problem

### ISSUE THREAD

**Issue by DanielLeyUX** [kickstartDS/cooper-website#13]
please check that the dropdown flies over the content below :) 
we had this issue solved in other projects already 

![image](https://github.com/user-attachments/assets/e12ed4d7-eaaf-4e9c-9840-d04b91a33d57)

**Comment by julrich** [comment]
Should be fixed in `ds-agency-premium` / `storyblok-starter-premium`, then, too!

**Comment by julrich** [comment]
@DanielLeyUX please check on your end, and close if fixed for you, too! (was already fixed in `ds-agency-premium`, version in Connecta was just outdated).
