### ISSUE TITLE
Hero Textbox Style

### ISSUE THREAD

**Issue by DanielLeyUX** [kickstartDS/cooper-website#15]
Wir sollten noch bei Connecta am Hero die Textbox abrunden 

ist es möglich, ohne wirklich aufwand, dass die box bei "position below" nicht transparent ist? 

![image](https://github.com/user-attachments/assets/1a821e29-faf0-49a0-89f7-4140d1543cce)

**Comment by fleven-kds** [comment]
@DanielLeyUX Soll die Box **nur** bei der `position: below` nicht mehr transparent sein?

**Comment by DanielLeyUX** [comment]
@fleven-kds ja, würde ich sagen. sonst schwebt die Box über dem Bild, da ist die Transparenz gut
