### ISSUE TITLE
Icon Picker: close/escape of modal not working

### ISSUE THREAD

**Issue by DanielLeyUX** [kickstartDS/cooper-website#3]
No escape from modal without selecting an icon

![image](https://github.com/user-attachments/assets/cc258a17-f93e-49a3-bc48-a12b3b5e2bb3)

**Comment by julrich** [comment]
This needs fixing of the icons in general first... meaning: all custom icons (this should be the set used on `ruhmesmeile` currently, to start) and all icons used by presets need to be added to the project itself (`Copper` and `Connecta`) explicitly:
https://github.com/kickstartDS/cooper-website/tree/main/token/dictionary/icons

The resulting icon sprite can then be added to the respective global project settings in Storyblok... which should in turn fix the icon picker. Which should also have a close / reset to none option, if I'm no misremembering... maybe just needs an update, too.

Icons used by presets should also be added / included in the starter itself... issue for that: https://github.com/kickstartDS/storyblok-starter/issues/26
